Repository neetjn/py-component-controller, pull requests merged in 2018-04, with the labels that each got.

#88 Issue 87 - Component root selector.
  docs/source/getting_started.rst
  pyscc/component.py
  pyscc/element.py
  tests/test_component.py
  tests/test_component_elements.py
  tests/utils.py
Labels: enhancement

#93 Issue 92 - Elements Stale Checks
  pyscc/element.py
  tests/test_component_elements.py
Labels: bug, enhancement

#99 0.2.2
  docs/source/component.rst
  docs/source/conf.py
  docs/source/service.rst
  pyscc/element.py
  pyscc/service.py
  setup.py
  tests/test_component.py
  tests/test_component_elements.py
  tests/test_service.py
Labels: bug, enhancement

#102 Encoded console dump to UTF8 before writing to file. (Issue #101)
  pyscc/controller.py
Labels: bug

#103 0.2.3
  docs/source/conf.py
  pyscc/controller.py
  setup.py
Labels: bug, enhancement
